#cloud-config
hostname: [hostname]
ssh_authorized_keys:
  - [ssh pubkey]

write_files:
  - container: ntp
    path: /etc/ntp.conf
    permissions: "0644"
    owner: root
    content: |
      192.168.0.55 iburst

      # Allow only time queries, at a limited rate, sending KoD when in excess.
      # Allow all local queries (IPv4, IPv6)
      restrict default nomodify nopeer noquery limited kod
      restrict 127.0.0.1
      restrict [::1]

rancher:
  network:
    dns:
      nameservers:
        - 192.168.4.4
      search:
        - [search domain]
    interfaces:
      eth0:
        dhcp: false
        address: 192.168.4.42/24
        gateway: 192.168.4.254
